[package]
name = "competitive_programming_library"
version = "0.1.0"
authors = ["hirok <hirokazu1020.gcj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
